name: Lint
on: push
jobs:
    Standards-And-Conventions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: action/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
            - name: Install Pyflakes
              run: pip install pyflakes
            - name: Run Pyflakes
              run: pyflakes .